/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;

import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author Sam
 */
public class Bingo extends javax.swing.JFrame {
    private ArrayList<Integer> uncalledNumbers;
    private ArrayList<Integer> calledNumbers;
    private Random gen;
    private int numCount;
    /**
     * Creates new form Bingo
     */
    public Bingo() {
        initComponents();
        this.setTitle("Sam's Bingo Caller");
        uncalledNumbers=new ArrayList<Integer>();
        calledNumbers=new ArrayList<Integer>();
        for(int num=1; num <= 75; num++){
            uncalledNumbers.add(num);
        }
        gen=new Random();
        numCount=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calledNumber = new javax.swing.JTextField();
        call = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        count = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bCalled = new javax.swing.JTextField();
        iCalled = new javax.swing.JTextField();
        nCalled = new javax.swing.JTextField();
        gCalled = new javax.swing.JTextField();
        oCalled = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(420, 250));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(calledNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 60, -1));

        call.setText("Call");
        call.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                callMousePressed(evt);
            }
        });
        getContentPane().add(call, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        reset.setText("Reset");
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        getContentPane().add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 50, -1));

        jLabel1.setText("Count");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel2.setText("Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel3.setText("B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 10, -1));

        jLabel4.setText("I");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 10, -1));
        getContentPane().add(bCalled, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, -1));
        getContentPane().add(iCalled, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, -1));
        getContentPane().add(nCalled, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 330, -1));

        gCalled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gCalledActionPerformed(evt);
            }
        });
        getContentPane().add(gCalled, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 330, -1));
        getContentPane().add(oCalled, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, -1));

        jLabel5.setText("N");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setText("G");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel7.setText("O");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void callMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_callMousePressed
        if(uncalledNumbers.size()>0){
            int number=uncalledNumbers.get(gen.nextInt(uncalledNumbers.size()));
            if(number>0&&number<=15){
                calledNumber.setText("B-"+String.valueOf(number));
            }
            else if(number>15&&number<=30){
                calledNumber.setText("I-"+String.valueOf(number));
            }
            else if(number>30&&number<=45){
                calledNumber.setText("N-"+String.valueOf(number));
            }
            else if(number>45&&number<=60){
                calledNumber.setText("G-"+String.valueOf(number));
            }
            else{
                calledNumber.setText("O-"+String.valueOf(number));
            }
            calledNumbers.add(number);
            uncalledNumbers.remove(uncalledNumbers.indexOf(number));
            ArrayList<Integer> sortedList=sortList(calledNumbers);
            String bNums="";
            String iNums="";
            String nNums="";
            String gNums="";
            String oNums="";
            for(int num:sortedList){
                if(num>0&&num<=15){
                    bNums+=num+", ";
                }
                else if(num>15&&num<=30){
                    iNums+=num+", ";
                }
                else if(num>30&&num<=45){
                    nNums+=num+", ";
                }
                else if(num>45&&num<=60){
                    gNums+=num+", ";
                }
                else{
                    oNums+=num+", ";
                }
            }
            bCalled.setText(bNums);
            iCalled.setText(iNums);
            nCalled.setText(nNums);
            gCalled.setText(gNums);
            oCalled.setText(oNums);
            numCount++;
            count.setText(String.valueOf(numCount));
        }
    }//GEN-LAST:event_callMousePressed

    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        calledNumbers=new ArrayList<Integer>();
        uncalledNumbers=new ArrayList<Integer>();
        for(int x=1; x<=75; x++){
            uncalledNumbers.add(x);
        }
        numCount=0;
        calledNumber.setText("");
        bCalled.setText("");
        iCalled.setText("");
        nCalled.setText("");
        gCalled.setText("");
        oCalled.setText("");
        count.setText("");
    }//GEN-LAST:event_resetMousePressed

    private void gCalledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gCalledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gCalledActionPerformed
    
    public ArrayList<Integer> sortList(ArrayList<Integer> unsortedList){
        ArrayList<Integer> input=new ArrayList<Integer>();
        for(int x: unsortedList){
            input.add(x);
        }
        ArrayList<Integer> output=new ArrayList<Integer>();
        for(int numsLeft=0; numsLeft<unsortedList.size(); numsLeft++){
            int min=input.get(0);
            for(int i:input){
                if(i<=min){
                    min=i;
                }
            }
            output.add(min);
            input.remove(input.indexOf(min));
        }
    return output;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bingo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bingo().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bCalled;
    private javax.swing.JButton call;
    private javax.swing.JTextField calledNumber;
    private javax.swing.JTextField count;
    private javax.swing.JTextField gCalled;
    private javax.swing.JTextField iCalled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nCalled;
    private javax.swing.JTextField oCalled;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables

}
